### PR TITLE
Add (( ips )) operator to generate IPs

### PR DESCRIPTION
**Pull request by sorenh**
Example uses:
```
meta:
  base_network: 1.2.3.4/24
  index: 20
  count: 2

ip: (( ips meta.base_network meta.index ))
ip_range: (( ips meta.base_network meta.index meta.count ))
```

should generate:
```
meta:
  base_network: 1.2.3.4/24
  index: 20
  count: 2

ip: 1.2.3.20
ip_range:
  - 1.2.3.20
  - 1.2.3.21
```

This is very handy if you're using the same manifests across several
identical environment where the only difference is their subnet. E.g.
one environment uses 10.0.1.0/24 and another uses 10.0.2.0/24, and the
proxy is always the fifth IP in the subnet, the default gateway is
always the third, and the last 10 are always reserved. You can now do:

```
#env1.yml
meta:
  base_network: 10.0.1.0/24
```

```
#env2.yml
meta:
  base_network: 10.0.2.0/24
```

```
#network.yml
network_details:
  gateway: (( ips meta.base_network 3 ))
  proxy: (( ips meta.base_network 5 ))
  reserved: (( ips meta.base_network -5 5 ))
```

spruce merge env1.yml network.yml:
```
meta:
  base_network: 10.0.1.0/24
network_details:
  gateway: 10.0.1.3
  proxy: 10.0.1.5
  reserved:
  - 10.0.1.251
  - 10.0.1.252
  - 10.0.1.253
  - 10.0.1.254
  - 10.0.1.255
```

### CODE REVIEW

**Comment by geofffranks** [comment]
Curious - what are you using spruce for? There is the static_ips operator, but it's tied very strongly to the structure of a BOSH manifest. I'm guessing you're using spruce for something else?

**Comment by sorenh** [comment]
I'm passing information into BOSH managed components about parts of the infrastructure that is not managed by BOSH.

E.g. each environment has a meta.base_network key which specifies a subnet. I know that my proxy and gateway are always the nth and mth IP in my subnet. Using this operator, I can calculate those details instead of having specify them individually for each environment and inevitably eventually forget an environment or mistype.

**Comment by geofffranks** [comment]
To me, the first example you provide here is counterintuitive. `1.2.3.4/24` is a cidr block for `1.2.3.0 - 1.2.3.255`, so an index of `20`, should return `10.2.3.20`, not `10.2.3.24` (assuming 0-based indexing equates to the network addr of a cidr block).

**Comment by sorenh** [comment]
@geofffranks I agree completely and that's actually what the code currently does. If you pass an IP (rather than a CIDR) it starts at the IP, but with a CIDR it starts at the beginning of the subnet, just like you suggest.    The PR description is from an earlier version of the patch where IP's and CIDR's were treated the same (and counting started from the given IP). The commit message and the docs are up-to-date with the correct behaviour, just not the PR description.

**Comment by geofffranks** [comment]
Ah, my mistake, I misread the tests `base_ip` as an expectation, not a starting point. What happens when an index offset and/or count exceed the range of the network? For example, 10.244.0.0/24 with a n offset of 270, or 10.244.0.0/28 with an offset of 1, but count of 28.

**Comment by sorenh** [comment]
There's no out-of-bounds checking, and it doesn't do modulo or anything:

    # foo.yml
    ips: (( ips "192.168.1.16/29" -1 3 ))

`spruce merge foo.yml` will yield:

    ip:
    - 192.168.1.23
    - 192.168.1.24
    - 192.168.1.25

Where .24 and .25 are outside the given subnet. Should we err out, saying they're exceeding the given subnet?

**Comment by geofffranks** [comment]
Yeah, can you add error checking for those cases?

**Comment by sorenh** [comment]
On it.

**Comment by sorenh** [comment]
That should do it.

**Pull request merged**
