### PR TITLE
Fix #62 - Fix infinity loop problem when assign static IPs

### LINKED ISSUE #62: Infinity loop when assign static IPs
In commit id 6f5a63a905c68477a4ff44d6779470fb47afafc9, Infinity loop occurs when reserve static IPs more then 256.

Following is an example.

```
$ cat template.yml
networks:
- name: cf1
  subnets:
  - static:
    - 10.0.0.2 - 10.0.1.254
jobs:
- name: foo
  templates:
  - name: bar
  instances: 1
  networks:
  - name: cf1
    static_ips: (( static_ips(0) ))
```

```
$ spruce -D merge template.yml
DEBUG> Processing file 'template.yml'
DEBUG> $.networks: not found upstream, adding it
DEBUG> $.jobs: not found upstream, adding it
DEBUG> parsing `(( static_ips(0) ))': looks like a (( static_ips ... )) operator
DEBUG>  arguments:
DEBUG>   #0: parsed as unquoted integer literal '0'
DEBUG>
DEBUG> patching up YAML by evaluating outstanding operators
DEBUG>
DEBUG> running (( static_ips ... )) operation at $.jobs.0.networks.0.static_ips
DEBUG>   determining what job context (( static_ips ... )) was called in
DEBUG>   got it.  $.jobs.0
DEBUG>
DEBUG>   extracting job name from $.jobs.0.name
DEBUG>   got it.  job is foo
DEBUG>
DEBUG>   determining how many instances of job foo there are
DEBUG>   got it.  there are 1 instances of foo
DEBUG>
DEBUG>   checking to see if the caller asked for enough static_ips to provision all job instances (need at least 1)
DEBUG>   looks good.  asking for 1 IPs for a job with 1 instances
DEBUG>
DEBUG>   determining the pool of static IPs from which to provision

# gone away!
```

### PR DESCRIPTION
**Pull request by kei-yamazaki**
Fixes #62

### CODE REVIEW

**Comment by filefrog** [comment]
LGTM :+1:

**Comment by geofffranks** [comment]
There appears to be a strange edge case with this when using even larger ranges. I added some debugging to show the IPs it was printing, and going from 10.1.1.0 to 11.1.1.0 resulted in some addresses being allocated multiple times:

```
IP range includes: 10.12.255.254
IP range includes: 10.12.255.255
IP range includes: 10.13.0.0
IP range includes: 10.13.0.0
IP range includes: 10.13.0.0
IP range includes: 10.13.0.1
IP range includes: 10.13.0.2
```

When rolling over on the third octet, the .0 addr duplicates, instead of repeating three times.

**Comment by kei-yamazaki** [comment]
Thanks for additional edge tests!
The problem of you pointed out was reproduced.

Now I fix and rebase the branch.

**Comment by filefrog** [comment]
Can you add tests to exercise the first and second octet rollovers?

**Comment by kei-yamazaki** [comment]
@filefrog Thanks for comment.
I fixed test in my previous commit.

**Comment by filefrog** [comment]
Thanks!

**Comment by geofffranks** [comment]
This was merged manually. GitHub apparently got confused about that.

**Pull request closed without merging**
