### PR TITLE
Operand Expression Support

### PR DESCRIPTION
**Pull request by filefrog**
All operators can now use the more flexible expression system for
operands, which is comprised of the following expressions:

  - A literal value (string, integer, floating point number, etc.)
  - A reference to some other part of the YAML document
  - The nil-value (null, ~ or ni)
  - Some combination of the above, using the alternates / logical-or
    operator, `||'

### CODE REVIEW

**Comment by filefrog** [comment]
Outstanding items on this PR:

- Documentation
- Short-circuit behavior: Given
```
foo: (( grab meta.first || nil || meta.second ))
```
should spruce

1. just ignore `meta.second` altogether (naïve solution)?
2. optimize `meta.second` out (to avoid the needless data-flow dependency) and possibly warning the user via stderr?
3.  throw an error and refuse to proceed until the weird call has been corrected (force the human to optimize it)?

**Comment by filefrog** [comment]
(btw, this should fix #51)

**Comment by longnguyen11288** [comment]
:+1:

**Comment by filefrog** [comment]
Pushed new commits to handle the short-circuit behavior (option 2).

Documentation forthcoming.

**Comment by geofffranks** [comment]
Looks like this breaks `(( grab thing1, thing2 ))` when using `thing1 || "default"`, and `(( concat thing1 || "default", thing2 ))`

**Comment by filefrog** [comment]
Yup,  poor stack discipline.  I will get a patch into this PR for that tonight

**Comment by filefrog** [comment]
Patched.

**Comment by jimconner** [comment]
We've been testing out the expr branch today, and it all looks really good. Nice work @filefrog

**Pull request merged**
