### PR TITLE
Add prune operator

### PR DESCRIPTION
**Pull request by JamesClonk**
Signed-off-by: Fabio Berchtold <fabio.berchtold@swisscom.com>

### CODE REVIEW

**Comment by JamesClonk** [comment]
This allows for easy creation cloud-config compatible bosh deployments with static_ips, as seen under the new `examples/pruning/*.yml`, without having to use or know the `--prune` flag in advance.

**Comment by jhunt** [comment]
A question on the proposed behavior.

Given `a.yml`, `b.yml` and `c.yml`:

```
--- # a.yml
meta:
  stuff: test
a: (( grab meta.stuff ))

--- # b.yml
meta:
  stuff: (( prune ))

--- # c.yml
meta:
  stuff: override
```

`(( prune ))` exhibits some surprising (to me, at least) behavior:

```
→  ./spruce merge a.yml b.yml c.yml
a: override
meta: {}
```

Parsing the templates in my head, `meta.stuff` is first set to "test", then pruned out, and then set to "override".  Then, `a` grabs the value of `meta.stuff` as "override"

But if you drop off `c.yml`, you get this:

```
$ ./spruce merge a.yml b.yml
a: test
meta: {}
```

In my head, `meta.stuff` was set to "test" and then pruned out, but is still somehow available for the `(( grab ... ))` operator at `a`.  I understand the technical reasoning, for wanting to prune out `networks` _after_ having used it for a `static_ips` call, but I'm not sure I like the resulting behavior from a user standpoint.

Is this desirable behavior?

**Comment by JamesClonk** [comment]
Yes, that is the intended behavior.

My intention was to make `(( prune ))` behave the same way as the `--prune` flag. So no matter where in the merge/yaml chain it occurs, it should always and only prune as a post-process after everything else is done and not interfere in any way with the merging itself.

From my understanding spruce first merges everything together before it starts doing any processing like `static_ips` and so on. Could it somehow be adapted to do the prune in order as specified by the yaml files, but still work with `static_ips` and other operators?
I wouldn't mind having to merge a `make_cloudconfig.yml` as the last file, so long as it allows me to transform a "normal" BOSH manifest into a BOSH-cloud-config manifest by pruning networks, resource_pools, etc..
But I need to be able to do this in just 1 merge with all yaml files at once, and not using the `--prune` flag.

**Comment by jhunt** [comment]
If you don't mind my asking, why doesn't `--prune` suffice?

**Comment by JamesClonk** [comment]
I'm currently using bosh-workspace with spiff for merging bosh manifest templates, but intend to switch over to using spruce with it and rewrite all our templates from scratch. But I didn't want to have to somehow pass multiple `--prune` flags into bosh-workspace' merging operation, escpecially depending whether or not I have a cloud-config or what deployment templates I'm going to use. For me it would be elegant to simply only have template files and not having to think about flags, as I want to write the new templates to be easily used with or without a cloud-config enabled BOSH.

**Comment by jhunt** [comment]
Good enough for me 😀
:+1:

**Comment by karampok** [comment]
Can this pull request be merged? Creates some inconsistencies in developments.
Thx!

**Comment by qu1queee** [comment]
Having the --prune flag logic in a command that can be use at any yml file is a need. This makes the pruning straightforward during the yml creation, specially when multiple hashes/keys need to be removed from a yml file. If we already can append,replace,etc from any yml, why not to be able to prune.

**Comment by jhunt** [comment]
Can the merge conflicts be resolved?

**Comment by JamesClonk** [comment]
@jhunt ok, I fixed the merge conflicts.

**Comment by karampok** [comment]
Cool! Thx!

**Pull request merged**
