### PR TITLE
Remove --concourse option

### LINKED ISSUE #226: Remove --concourse flag
The --concourse flag is now deprecated. It should be removed after a suitable grace period

### PR DESCRIPTION
**Pull request by sorenh**
Fixes #226

### CODE REVIEW

**Comment by geofffranks** [comment]
Thanks! This looks good, just need to sit on it for a little bit before merging

**Comment by drnic** [comment]
One data point: in the Concourse Tutorial I've switched to showing ppl the `((variable))` syntax for parameters rather than the old `{{variable}}` style https://concoursetutorial.com/basics/parameters/

**Comment by jhunt** [comment]
Has this been sat on enough?

**Comment by geofffranks** [comment]
Yep. merged out of band due to merge conflicts, but this is now on master.

**Pull request closed without merging**
