### PR TITLE
New `spruce diff` command, finally.

### PR DESCRIPTION
**Pull request by jhunt**

### CODE REVIEW

**Comment by jhunt** [comment]
Having used this with some real-world (and fairly complicated) BOSH manifests, I'm leaning towards adding in some additional features:

- A `-p` / `--patch` option that will generate a patch (YAML) file that, when merged as `a.yml patch.yml` &rarr; `b.yml` (that is, what spruce operators would I need to use to go from `a.yml` to `b.yml`
- A `--skip` option that would ignore the given paths when calculating the diff.  Can be passed multiple times.  It would be nice to support suffix matching (i.e. `--skip password` would skip all `password:` keys, regardless of ancestry)
- A `--summarize` option that only prints the changes, without the associated values
- `--debug` and `--trace` support for debugging the diff algorithm

**Comment by geofffranks** [comment]
I'd also like to see some tests on re-ordering of lists (with scalars, maps, and combinations for their elements)

I'm onboard with `--skip`, `--debug`, `--trace`. Need to know more behind the use cases/motivation for `--summarize`. `--patch` seems like it would be either difficult to implement properly (if you really mean to have spruce decide what operators to use in certain situations), or misleading (and giving people non-operator properties where grab/static_ips/other operators should be used).

**Comment by jhunt** [comment]
screen shot 2016-11-20 at 3 45 22 pm

**Comment by jhunt** [comment]
The `--summary` command would produce output like above, except for the particulars of changed/added/remove values (just that the keys changed).

I played with an implementation of `--patch` last night and it worked well outside of simple (non-keyed) lists.  Not sure it's worth it.

**Comment by geofffranks** [comment]
I'd like to see it identify changes like this:

first:
```
jobs:
- name: first_job
- name: second_job
```
second:
```
jobs:
- name: one_point_five_job
- name: second_job
- name: first_job
```

as adding `one_point_five_job`, and moving `first_job` from first to third

**Comment by HeavyWombat** [comment]
Looking forward to see that in action in Spruce. Where I work, we created something very similar to diff BOSH deployment manifest without the need of BOSH itself. It is written in Ruby, so it is not of use here, but there are some features that you also consider putting into the backlog for the diff here.

One thing that helps us is an extended check for strings that get changed. For example with certificates it happened that the actual content did not change, but only a couple of white spaces were different. So we highlight that by showing the spaces in a diff if the content is the same if you would ignore the white spaces (like other diff tools do that, too).

**Comment by jhunt** [comment]
Given that this is diffing YAML post-parse, it would seem to me that a difference in whitespace was intentional and merits review.  Extra newlines or columnar spacing that do not directly affect the value is removed during the YAML parse.

**Comment by jhunt** [comment]
Tests added for the simple list re-arrangement case.  We can come back and revisit the more semantic "things were reordered, but otherwise unchanged" diff behavior.

**Pull request merged**
