### PR TITLE
Introduce dyff as the diff package

### LINKED ISSUE #285: Spruce diff does not show the changes in array order if array element is a hash
```
$ cat foo.yml 
foo:
  - name: one
    prop: one
  - name: two
    prop: two
  - name: three
    prop: three

$ cat bar.yml 
foo:
  - name: one
    prop: one
  - name: three
    prop: three
  - name: two
    prop: two

$ spruce diff foo.yml bar.yml 
both files are semantically equivalent; no differences found!
```

### PR DESCRIPTION
**Pull request by HeavyWombat**
Use [`dyff`](https://github.com/homeport/dyff) package to create the diff output. It supports additional checks for order changes in lists and a compact output style.

I tried to update as few dependencies as possible, but the following updates were necessary:
```sh
godep update -v github.com/smartystreets/...
godep update golang.org/x/sys/unix
godep update github.com/mattn/go-isatty
godep update gopkg.in/yaml.v2
godep save ./...
```

Also, I had to add `context.Background()` to the server test case to fix a NilPointer panic.

This should fix #285.

Example:
image

### CODE REVIEW

**Comment by HeavyWombat** [comment]
@geofffranks Have you had a chance to take a look at this PR? Thanks in advance.

**Comment by geofffranks** [comment]
Sorry, I thought I was waiting still for dependency updates. Will try to look tomorrow

**Comment by geofffranks** [comment]
Seems like there are some issues running tests now after the dependency updates. May take a little bit to get this released officially

**Comment by HeavyWombat** [comment]
Oh, really? I am sorry for the dependency problems. I thought with the vendor directory everything should be right where it is suppose to be.

I already started to look into a migration to Go modules. In theory, it should get better the Go modules.

**Comment by geofffranks** [comment]
Looks like it's a problem with just my laptop. CI looks fine, and another laptop i have works fine.

**Pull request merged**
