### PR TITLE
Add load operator to Spruce

### PR DESCRIPTION
**Pull request by HeavyWombat**
Add code and test cases for `(( load ... ))` operator, which interprets the
provided literal argument as a file location. The file is either loaded
locally from the file system or as a URI remotely. The file content must be
valid YAML or JSON and is then inserted into the tree structure.

Main use case is for Concourse centric tasks of Spruce, where it is often
nice to reuse already existing pipeline YAMLs in different files. Since Concourse
makes it hard to define nice Spruce merging rules, loading the YAML content
can help a lot in those instances.

### CODE REVIEW

**Comment by geofffranks** [comment]
Am I right in thinking that this doesn't do any operator evaluation of the content being loaded, it just grabs raw yml/json data and puts it in place?

**Comment by HeavyWombat** [comment]
Good point. I have not really thought about that one. I always assumed to just grab the raw YAML/JSON. Trying to evaluate operators in the loaded content can open some weird scenarios, for example if there are `grab` operators in there, would they assume their root would be the document they are in or the one they are loaded into. What do you think about evaluating operators? At the moment, I tend to say that this operator should behave like `file` and just load the content, but I am open to more feedback. And yes, certainly, I can update the documentation.

**Comment by geofffranks** [comment]
I would have thought they might be handy for things like loading in concourse structures into files, but there are a ton of difficulties in trying to figure out the evaluation and merge orders from data that’s currently unknown to spruce when it does those steps. 

I’m in favor of just loading raw data from the files and not evaluating anything. People can always script out a spruce merge of those files prior to being loaded in another merge if that’s necessary as a workaround.

**Comment by HeavyWombat** [comment]
@geofffranks Thanks for the feedback. I rebased my branch and updated the documentation.

**Comment by geofffranks** [comment]
Thanks!

**Pull request merged**
