### PR TITLE
Teach param how to have default arguments

### PR DESCRIPTION
**Pull request by novas0x2a**

### CODE REVIEW

**Comment by geofffranks** [comment]
Thanks! I'm a little confused how this works in practice. Does the param with a default advertise itself somehow with messaging, or is it the same as just setting a value in the yaml and someone merging on top of it to change that value?

**Comment by novas0x2a** [comment]
the latter, yeah; either it gets overwritten entirely on merge, or it returns a value instead of throwing an error. It's not great (what I think I'd actually want it to do is more like `(( param "a thing" <EVAL AS NEW OPERATOR> ))` so things like `(( param "a thing" concat other.thing "meow"))` would work, but I wasn't quite sure how to get that. With my impl here, you can get that effect with:
```
defaultThing: (( complicated operator goes here ))
thing: (( param "thing" defaultThing))
```
which isn't quite as neat but does work.

**Comment by geofffranks** [comment]
So, what's the purpose of having the default param then? Since any key is overridable, giving it a value is essentially giving a default. The role of param was to force consumers of the template to override with a value that made sense for their specific use case (e.g. an IP, or password).

**Comment by novas0x2a** [comment]
I was using it as a self documenting parameter, but I can use a yaml
comment for that too, so it's not the end of the world if you don't want to
take this (I won't be offended 😀). Ideally I'd make it do the other thing
you suggested at the beginning (the "press enter to select the default"
case) but that seems like it might need a change to the operator interface
to do.

**Comment by geofffranks** [comment]
Are you parsing out the params somehow with a tool to provide documentation around params for an individual template?

**Comment by novas0x2a** [comment]
Nah, i'm not doing anything smart with it right now; i'll reopen if i have something a little more baked/thought-through

**Pull request closed without merging**
