### PR TITLE
Added Vault KV v2 support

### PR DESCRIPTION
**Pull request by yurinnick**
Added: Vault KV v2 API support

My first day of Go coding, please be gentle :)

### CODE REVIEW

**Comment by yurinnick** [comment]
#273

**Comment by yurinnick** [comment]
@geofffranks could you provide any feedback please? Any chance to get it merged?

**Comment by geofffranks** [comment]
Sorry for the delay, life's pretty busy. This looks really good, especially for a first time with go programming! There are a couple places where you have some code being added but commented out, and some typos (responce vs response, possiable vs possible). The main thing that I'd want changed though is the error message output. Can you add the engine back in to the error message, so that it includes something that can be easily copy/pasted for use with [safe](https://github.com/starkandwayne/safe), to make it easier to find/fix typos, gen creds, or otherwise fix the issue of the secret not being found?

Also, it looks like you removed the mocked copy of `exit` values in `main_test.go` under the TestExamples section. How come?

**Comment by yurinnick** [comment]
Thanks for the feedback! I'll make appropriate changes to the code soon.

>Also, it looks like you removed the mocked copy of exit values in main_test.go under the TestExamples section. How come?

I got a build failure while running tests due to this block. I didn't find better solution for this, please advise.

```shell
$ go version
go version go1.11.2 darwin/amd64

$ make test
go list ./... | grep -v vendor | xargs go test
# github.com/geofffranks/spruce/cmd/spruce
cmd/spruce/main_test.go:2197:2: rc declared but not used
vet: typecheck failures
ok  	github.com/geofffranks/spruce	0.732s
FAIL	github.com/geofffranks/spruce/cmd/spruce [build failed]
ok  	github.com/geofffranks/spruce/log	(cached)
make: *** [test] Error 1
```

**Comment by geofffranks** [comment]
Looks like that’s a result of something new in go 1.11.2. I’ll get that updated on main, and you won’t need to worry about that for your PR.

**Comment by geofffranks** [comment]
Thank you!

**Pull request merged**
